[runtime]
auto_reload = "off"
watcher_on_save = "lazy"
auto_instantiate = true
on_cell_change = "autorun"

[experimental]

[completion]
activate_on_typing = true
copilot = false

[save]
autosave_delay = 1000
format_on_save = true
autosave = "after_delay"

[formatting]
line_length = 79

[keymap]
preset = "default"

[package_management]
manager = "uv"

[snippets]
custom_paths = []
include_default_snippets = true

[ai]
rules = ""

[display]
cell_output = "above"
theme = "light"
default_width = "medium"
code_editor_font_size = 14
dataframes = "rich"

[server]
follow_symlink = false
browser = "default"
