name: ci

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
        - "dashboard.py"
        - ".python-version"
  pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
    
      - name: ⬇️ Install Hatch
        uses: pypa/hatch@install

      - name: run dashboard
        run: hatch run dashboard.py
