name: ci

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:


jobs:
  test-latest-linux:
    name: Test (Linux)
    runs-on: ubuntu-latest

    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - uses: actions/checkout@v4
    
      - name: ⬇️ Install Hatch
        uses: pypa/hatch@install

      - name: run dashboard
        run: hatch dashboard.py