name: ci

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
      

jobs:
  test-latest-linux:
    name: Test (Linux)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
    
      - name: ⬇️ Install Hatch
        uses: pypa/hatch@install

      - name: run dashboard
        run: hatch run dashboard.py